[package]
name = "art2map-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
ctrlc = "3.2.2"
reqwest = {version= "0.11.10", features = ["blocking"]}
